package com.prography.ui.configuration

import androidx.annotation.ColorRes
import com.prography.ui.R
import com.prography.domain.configuration.ThemeType

/**
 * Created by MyeongKi.
 */
data class ColorsTheme(
    @ColorRes val primaryNormal: Int = 0,
    @ColorRes val primaryStrong: Int = 0,
    @ColorRes val primaryHeavy: Int = 0,
    @ColorRes val labelNormal: Int = 0,
    @ColorRes val labelStrong: Int = 0,
    @ColorRes val labelNeutral: Int = 0,
    @ColorRes val labelAlternative: Int = 0,
    @ColorRes val labelAssistive: Int = 0,
    @ColorRes val labelDisable: Int = 0,
    @ColorRes val backgroundRegularNormal: Int = 0,
    @ColorRes val backgroundAlternative: Int = 0,
    @ColorRes val backgroundElevatedNormal: Int = 0,
    @ColorRes val backgroundElevatedAlternative: Int = 0,
    @ColorRes val interactionInactive: Int = 0,
    @ColorRes val interactionDisable: Int = 0,
    @ColorRes val lineRegularNormal: Int = 0,
    @ColorRes val lineRegularNeutral: Int = 0,
    @ColorRes val lineRegularAlternative: Int = 0,
    @ColorRes val lineRegularStrong: Int = 0,
    @ColorRes val lineSolidNormal: Int = 0,
    @ColorRes val lineSolidNeutral: Int = 0,
    @ColorRes val lineSolidAlternative: Int = 0,
    @ColorRes val lineSolidStrong: Int = 0,
    @ColorRes val fillNormal: Int = 0,
    @ColorRes val fillStrong: Int = 0,
    @ColorRes val fillAlternative: Int = 0,
    @ColorRes val statusPositive: Int = 0,
    @ColorRes val statusCautionary: Int = 0,
    @ColorRes val statusNegative: Int = 0,
    @ColorRes val accentLime: Int = 0,
    @ColorRes val accentCyan: Int = 0,
    @ColorRes val accentLightBlue: Int = 0,
    @ColorRes val accentViolet: Int = 0,
    @ColorRes val accentPink: Int = 0,
    @ColorRes val accentRedOrange: Int = 0,
    @ColorRes val accentPurple: Int = 0,
    @ColorRes val dimmer: Int = 0,
    @ColorRes val inversePrimary: Int = 0,
    @ColorRes val inverseBackground: Int = 0,
    @ColorRes val inverseLabel: Int = 0,
    @ColorRes val socialKakao: Int = 0,
    @ColorRes val staticWhite: Int = 0,
    @ColorRes val staticBlack: Int = 0
)

fun darkThemeColorsTheme() = ColorsTheme(
    primaryNormal = R.color.blue_60,
    primaryStrong = R.color.blue_55,
    primaryHeavy = R.color.blue_50,
    labelNormal = R.color.cool_neutral_99,
    labelStrong = R.color.common_100,
    labelNeutral = R.color.c2c4c8,
    labelAlternative = R.color.aeb0b6,
    labelAssistive = R.color.aeb0b6,
    labelDisable = R.color.cool_neutral_16,
    backgroundRegularNormal = R.color.cool_neutral_15,
    backgroundAlternative = R.color.cool_neutral_05,
    backgroundElevatedNormal = R.color.cool_neutral_17,
    backgroundElevatedAlternative = R.color.cool_neutral_07,
    interactionInactive = R.color.cool_neutral_40,
    interactionDisable = R.color.cool_neutral_22,
    lineRegularNormal = R.color.cool_neutral_32,
    lineRegularNeutral = R.color.cool_neutral_28,
    lineRegularAlternative = R.color.cool_neutral_22,
    lineRegularStrong = R.color.c2c4c8,
    lineSolidNormal = R.color.cool_neutral_25,
    lineSolidNeutral = R.color.cool_neutral_23,
    lineSolidAlternative = R.color.cool_neutral_22,
    lineSolidStrong = R.color.cool_neutral_50,
    fillNormal = R.color.cool_neutral_22,
    fillStrong = R.color.cool_neutral_28,
    fillAlternative = R.color.alternative_12,
    statusPositive = R.color.green_60,
    statusCautionary = R.color.orange_60,
    statusNegative = R.color.red_60,
    accentLime = R.color.lime_60,
    accentCyan = R.color.cyan_60,
    accentLightBlue = R.color.light_blue_60,
    accentViolet = R.color.violet_60,
    accentPink = R.color.pink_60,
    accentRedOrange = R.color.red_orange_60,
    accentPurple = R.color.purple_60,
    dimmer = R.color._171719_74,
    inversePrimary = R.color.blue_50,
    inverseBackground = R.color.common_100,
    inverseLabel = R.color.cool_neutral_10,
    socialKakao = R.color.fee500,
    staticWhite = R.color.common_100,
    staticBlack = R.color.common_0
)

fun lightThemeColorsTheme() = ColorsTheme(
    primaryNormal = R.color.blue_50,
    primaryStrong = R.color.blue_45,
    primaryHeavy = R.color.blue_40,
    labelNormal = R.color.cool_neutral_10,
    labelStrong = R.color.common_0,
    labelNeutral = R.color._2e2f33_88,
    labelAlternative = R.color._37383c_61,
    labelAssistive = R.color._37383c_28,
    labelDisable = R.color._37383c_16,
    backgroundRegularNormal = R.color.common_100,
    backgroundAlternative = R.color.cool_neutral_99,
    backgroundElevatedNormal = R.color.common_100,
    backgroundElevatedAlternative = R.color.cool_neutral_99,
    interactionInactive = R.color.cool_neutral_70,
    interactionDisable = R.color.cool_neutral_98,
    lineRegularNormal = R.color._70737c_22,
    lineRegularNeutral = R.color._70737c_16,
    lineRegularAlternative = R.color._70737c_8,
    lineRegularStrong = R.color._70737c_52,
    lineSolidNormal = R.color.cool_neutral_96,
    lineSolidNeutral = R.color.cool_neutral_97,
    lineSolidAlternative = R.color.cool_neutral_98,
    lineSolidStrong = R.color.cool_neutral_80,
    fillNormal = R.color._70737c_8,
    fillStrong = R.color._70737c_16,
    fillAlternative = R.color._70737c_5,
    statusPositive = R.color.green_50,
    statusCautionary = R.color.orange_50,
    statusNegative = R.color.red_50,
    accentLime = R.color.lime_50,
    accentCyan = R.color.cyan_50,
    accentLightBlue = R.color.light_blue_50,
    accentViolet = R.color.violet_50,
    accentPink = R.color.pink_50,
    accentRedOrange = R.color.red_orange_50,
    accentPurple = R.color.purple_50,
    dimmer = R.color._171719_52,
    inversePrimary = R.color.blue_60,
    inverseBackground = R.color.cool_neutral_15,
    inverseLabel = R.color.cool_neutral_99,
    socialKakao = R.color.fee500,
    staticWhite = R.color.common_100,
    staticBlack = R.color.common_0
)

fun ThemeType.toColors(): ColorsTheme = when (this) {
    ThemeType.DARK -> {
        darkThemeColorsTheme()
    }

    ThemeType.LIGHT -> {
        lightThemeColorsTheme()
    }
}