package com.prography.configuration

import androidx.annotation.ColorRes
import com.prography.domain.configuration.ThemeType

/**
 * Created by MyeongKi.
 */
data class ColorsTheme(
    @ColorRes val primaryNormal: Int = 0,
    @ColorRes val primaryStrong: Int = 0,
    @ColorRes val primaryHeavy: Int = 0,
    @ColorRes val labelNormal: Int = 0,
    @ColorRes val labelStrong: Int = 0,
    @ColorRes val labelNeutral: Int = 0,
    @ColorRes val labelAlternative: Int = 0,
    @ColorRes val labelAssistive: Int = 0,
    @ColorRes val labelDisable: Int = 0,
    @ColorRes val backgroundRegularNormal: Int = 0,
    @ColorRes val backgroundRegularAlternative: Int = 0,
    @ColorRes val backgroundElevatedNormal: Int = 0,
    @ColorRes val backgroundElevatedAlternative: Int = 0,
    @ColorRes val interactionInactive: Int = 0,
    @ColorRes val interactionDisable: Int = 0,
    @ColorRes val lineNormal: Int = 0,
    @ColorRes val lineNeutral: Int = 0,
    @ColorRes val lineAlternative: Int = 0,
    @ColorRes val lineStrong: Int = 0,
    @ColorRes val lineSolidNormal: Int = 0,
    @ColorRes val lineSolidNeutral: Int = 0,
    @ColorRes val lineSolidAlternative: Int = 0,
    @ColorRes val lineSolidStrong: Int = 0,
    @ColorRes val fillNormal: Int = 0,
    @ColorRes val fillStrong: Int = 0,
    @ColorRes val fillAlternative: Int = 0,
    @ColorRes val statusPositive: Int = 0,
    @ColorRes val statusCautionary: Int = 0,
    @ColorRes val statusNegative: Int = 0,
    @ColorRes val staticWhite: Int = 0,
    @ColorRes val staticBlack: Int = 0,
    @ColorRes val accentLime: Int = 0,
    @ColorRes val accentCyan: Int = 0,
    @ColorRes val accentLightBlue: Int = 0,
    @ColorRes val accentViolet: Int = 0,
    @ColorRes val accentPink: Int = 0,
    @ColorRes val accentRedOrange: Int = 0,
    @ColorRes val accentPurple: Int = 0,
    @ColorRes val materialDimmer: Int = 0,
    @ColorRes val inversePrimary: Int = 0,
    @ColorRes val inverseBackground: Int = 0,
    @ColorRes val inverseLabel: Int = 0,
    @ColorRes val kakaoColor: Int = 0,
)

fun darkThemeColorsTheme() = ColorsTheme(
    primaryNormal = R.color.primaryNormalDark,
    primaryStrong = R.color.primaryStrongDark,
    primaryHeavy = R.color.primaryHeavyDark,
    labelNormal = R.color.labelNormalDark,
    labelStrong = R.color.labelStrongDark,
    labelNeutral = R.color.labelNeutralDark,
    labelAlternative = R.color.labelAlternativeDark,
    labelAssistive = R.color.labelAssistiveDark,
    labelDisable = R.color.labelDisableDark,
    backgroundRegularNormal = R.color.backgroundRegularNormalDark,
    backgroundRegularAlternative = R.color.backgroundRegularAlternativeDark,
    backgroundElevatedNormal = R.color.backgroundElevatedNormalDark,
    backgroundElevatedAlternative = R.color.backgroundElevatedAlternativeDark,
    interactionInactive = R.color.interactionInactiveDark,
    interactionDisable = R.color.interactionDisableDark,
    lineNormal = R.color.lineNormalDark,
    lineNeutral = R.color.lineNeutralDark,
    lineAlternative = R.color.lineAlternativeDark,
    lineStrong = R.color.lineStrongDark,
    lineSolidNormal = R.color.lineSolidNormalDark,
    lineSolidNeutral = R.color.lineSolidNeutralDark,
    lineSolidAlternative = R.color.lineSolidAlternativeDark,
    lineSolidStrong = R.color.lineSolidStrongDark,
    fillNormal = R.color.fillNormalDark,
    fillStrong = R.color.fillStrongDark,
    fillAlternative = R.color.fillAlternativeDark,
    statusPositive = R.color.statusPositiveDark,
    statusCautionary = R.color.statusCautionaryDark,
    statusNegative = R.color.statusNegativeDark,
    staticWhite = R.color.staticWhite,
    staticBlack = R.color.staticBlack,
    accentLime = R.color.accentLimeDark,
    accentCyan = R.color.accentCyanDark,
    accentLightBlue = R.color.accentLightBlueDark,
    accentViolet = R.color.accentVioletDark,
    accentPink = R.color.accentPinkDark,
    accentRedOrange = R.color.accentRedOrangeDark,
    accentPurple = R.color.accentPurpleDark,
    materialDimmer = R.color.materialDimmerDark,
    inversePrimary = R.color.inversePrimaryDark,
    inverseBackground = R.color.inverseBackgroundDark,
    inverseLabel = R.color.inverseLabelDark,
    kakaoColor = R.color.kakao,
)

fun lightThemeColorsTheme() = ColorsTheme(
    primaryNormal = R.color.primaryNormalLight,
    primaryStrong = R.color.primaryStrongLight,
    primaryHeavy = R.color.primaryHeavyLight,
    labelNormal = R.color.labelNormalLight,
    labelStrong = R.color.labelStrongLight,
    labelNeutral = R.color.labelNeutralLight,
    labelAlternative = R.color.labelAlternativeLight,
    labelAssistive = R.color.labelAssistiveLight,
    labelDisable = R.color.labelDisableLight,
    backgroundRegularNormal = R.color.backgroundRegularNormalLight,
    backgroundRegularAlternative = R.color.backgroundRegularAlternativeLight,
    backgroundElevatedNormal = R.color.backgroundElevatedNormalLight,
    backgroundElevatedAlternative = R.color.backgroundElevatedAlternativeLight,
    interactionInactive = R.color.interactionInactiveLight,
    interactionDisable = R.color.interactionDisableLight,
    lineNormal = R.color.lineNormalLight,
    lineNeutral = R.color.lineNeutralLight,
    lineAlternative = R.color.lineAlternativeLight,
    lineStrong = R.color.lineStrongLight,
    lineSolidNormal = R.color.lineSolidNormalLight,
    lineSolidNeutral = R.color.lineSolidNeutralLight,
    lineSolidAlternative = R.color.lineSolidAlternativeLight,
    lineSolidStrong = R.color.lineSolidStrongLight,
    fillNormal = R.color.fillNormalLight,
    fillStrong = R.color.fillStrongLight,
    fillAlternative = R.color.fillAlternativeLight,
    statusPositive = R.color.statusPositiveLight,
    statusCautionary = R.color.statusCautionaryLight,
    statusNegative = R.color.statusNegativeLight,
    staticWhite = R.color.staticWhite,
    staticBlack = R.color.staticBlack,
    accentLime = R.color.accentLimeLight,
    accentCyan = R.color.accentCyanLight,
    accentLightBlue = R.color.accentLightBlueLight,
    accentViolet = R.color.accentVioletLight,
    accentPink = R.color.accentPinkLight,
    accentRedOrange = R.color.accentRedOrangeLight,
    accentPurple = R.color.accentPurpleLight,
    materialDimmer = R.color.materialDimmerLight,
    inversePrimary = R.color.inversePrimaryLight,
    inverseBackground = R.color.inverseBackgroundLight,
    inverseLabel = R.color.inverseLabelLight,
    kakaoColor = R.color.kakao,
)


fun ThemeType.toColors(): ColorsTheme = when (this) {
    ThemeType.DARK -> {
        darkThemeColorsTheme()
    }

    ThemeType.LIGHT -> {
        lightThemeColorsTheme()
    }
}