/**
 * Created by MyeongKi.
 */
enum class GwasuwonRouteHost {
    SIGN_IN,
    SIGN_UP,
    LESSONS,
    LESSON_INVITED,
    CREATE_LESSON,
    LESSON_DETAIL,
    EXTENSION_LESSON,
    SUCCESS_CREATE_LESSON,
    LESSON_INFO_DETAIL,
    INVITE_STUDENT_QR,
    LESSON_CERTIFICATION_QR,
    LESSON_CONTRACT_QR,
    ;
}